version: '3'

services:
  db:
    image: mysql:8
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: pass123
      MYSQL_USER: babo
      MYSQL_PASSWORD: pass123
      restart: always
      DATABASE: shop
    ports:
      - 3336:3306

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      - PMA_ARBITRARY

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - 1080:1080
      - 1025:1025